# Generated by Django 3.2.9 on 2025-08-27 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(blank=True, choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Sold', 'Sold')], max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=100)),
                ('worker_type', models.CharField(choices=[('mesthri', 'Mesthri'), ('mason', 'Mason'), ('material', 'Material'), ('chital', 'Chital'), ('painter', 'Painter'), ('labour_painter', 'Labour (Painter)'), ('electrician', 'Electrician'), ('labour_electrician', 'Labour (Electrician)'), ('plumber', 'Plumber'), ('labour_plumber', 'Labour (Plumber)'), ('carpenter', 'Carpenter')], max_length=50)),
                ('weekly_wage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='records.project')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(choices=[('Cement', 'Cement'), ('Bricks', 'Bricks (playas)'), ('Sand_E', 'M-sand'), ('Sand_B', 'P-sand'), ('Jelly_Q', 'Jelly (¼ size)'), ('Jelly_H', 'Jelly (3/4 size)'), ('Jelly_P', 'Jelly (1.5 size)'), ('Jelly_S', 'Jelly (Bolder)'), ('Tiles_Q', 'Tiles (TMT(8mm))'), ('Tiles_H', 'Tiles (TMT(10mm))'), ('Tiles_P', 'Tiles (TMT(12mm))'), ('Tiles_S', 'Tiles (TMT(16mm))'), ('Tiles_R', 'Tiles (TMT(20mm))'), ('Paints', 'Paints'), ('Wood_M_Teak', 'Wood(main_door(teak))'), ('Wood_M_Saal', 'Wood(main_door(saal))'), ('Wood_M_Mahagani', 'Wood(main_door(mahagani))'), ('Wood_W_Mahagani', 'Wood(windows(mahagani))'), ('Wood_W_Upvc', 'Wood(windows(upvc))'), ('Electronics_Wire', 'Electronics(wire(2.5sq,1.5sq,1sq))'), ('Electronics_Plug', 'Electronics(plug)'), ('Electronics_LED', 'Electronics(LEDLight(ceiling_4inch,elevation_3inch))'), ('Electronics_Tube', 'Electronics(Tubelight)'), ('Plumbing_Upvc', 'Plumbing(upvc(1inch,3/4inch))'), ('Plumbing_Pvc', 'Plumbing(pvc(4inch,2.5inch,1.5inch))'), ('Plumbing_Fittings', 'Plumbing(Fittings(Bathroom,Kitchen))'), ('Grill', 'Grill(grill,gate)')], max_length=50)),
                ('quantity_purchased', models.IntegerField(default=0)),
                ('quantity_used', models.IntegerField(default=0)),
                ('quantity_sold', models.IntegerField(default=0)),
                ('supplier_name', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='records.project')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('members_count', models.PositiveIntegerField(default=1)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='records.worker')),
            ],
            options={
                'unique_together': {('worker', 'date')},
            },
        ),
    ]
