# Generated by Django 3.2.9 on 2025-08-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='weekly_wage',
            field=models.IntegerField(),
        ),
    ]
