# Generated by Django 3.2.9 on 2025-08-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_worker_weekly_wage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
