# Generated by Django 3.2.9 on 2025-09-03 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_project_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerattendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=10),
        ),
        migrations.AlterField(
            model_name='workerattendance',
            name='members_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='workerattendance',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workerattendance',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.worker'),
        ),
        migrations.AlterUniqueTogether(
            name='workerattendance',
            unique_together=set(),
        ),
    ]
