# Generated by Django 3.2.9 on 2025-09-04 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20250903_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerattendance',
            name='status',
        ),
    ]
