# Generated by Django 3.2.9 on 2025-09-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_remove_workerattendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerattendance',
            name='daily_wage',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workerattendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=20),
        ),
    ]
