# Generated by Django 3.2.9 on 2025-09-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_auto_20250904_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='worker_type',
            field=models.CharField(choices=[('Mesthri', 'Mesthri'), ('Meson', 'Meson'), ('Mamtiyal', 'Mamtiyal'), ('Sittaal', 'Sittaal'), ('Painter', 'Painter'), ('Electrician', 'Electrician'), ('Plumber', 'Plumber')], max_length=50),
        ),
        migrations.AlterField(
            model_name='workerattendance',
            name='daily_wage',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
