# Generated by Django 3.2.9 on 2025-09-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_auto_20250904_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
