# Generated by Django 3.2.9 on 2025-09-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_worker_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='weekly_wage',
            field=models.IntegerField(default=0),
        ),
    ]
